# Generated by Django 6.0.5 on 2026-08-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0009_remove_jobrequirement_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('job_code', models.CharField(max_length=50, unique=True)),
                ('job_description', models.TextField(blank=True)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('salary_package', models.DecimalField(decimal_places=2, help_text='Annual CTC in your currency', max_digits=12)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('experience', models.DecimalField(decimal_places=1, default=0, help_text='Required experience in years', max_digits=4)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship')], default='Full-time', max_length=50)),
                ('roles_and_responsibilities', models.TextField(blank=True)),
                ('key_responsibilities', models.TextField(blank=True)),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
                ('required_skills', models.ManyToManyField(blank=True, to='students.skill')),
                ('required_qualifications', models.ManyToManyField(blank=True, to='jobs.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('OPTED_OUT', 'Opted Out')], default='APPLIED', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobrequirement')),
            ],
        ),
    ]
