# Generated by Django 6.0.5 on 2026-08-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequirement',
            name='required_qualifications',
        ),
    ]
