# Generated by Django 6.0.5 on 2026-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_jobrequirement_required_qualifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='required_qualifications',
            field=models.ManyToManyField(blank=True, to='students.education'),
        ),
    ]
