# Generated by Django 6.0.5 on 2026-08-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0007_rename_experienct_studentprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile'),
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
