# Generated by Django 6.0.5 on 2026-08-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_jobrequirement_company_delete_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequirement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='required_qualifications',
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='required_skills',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='JobRequirement',
        ),
    ]
